### ISSUE TITLE
Launch Phase 2 of a three-phase project on carpentries.org content redesign

### ISSUE THREAD

**Issue by kariljordan** [carpentries/strategic-plan#32]
Phase 1 work constituted reading on, researching and learning about web accessibility as a necessary prerequisite to signing up for a design thinking workshop as a team.

In phase 2, Carpentries Team goes through design thinking process and finds a designer. In this phase, we will need to sit in for design thinking workshops for a percentage of our Professional Development time as a team. This will help us as we work on redesigning content placement on The Carpentries website, with accessibility and discoverability as the two main goals of the redesign.

The three phases are: 
- phase 1: deep dive into web accessibility (Q4 2020)
- phase 2: design thinking workshop with web accessibility in mind (Q1 2021)
- phase 3: website redesign (Q2 2021 onwards)

**Comment by serahrono** [comment]
Community Development Team has made good progress in this regard, particularly in thinking about challenges and gaps in the current design of our website and handbook and summarising these in a way that will be useful for the designer. We have identified a designer, and hope to start work with them in Q2 2021. Because of our Core Team retreat and all prep work around it, our Design Thinking work will now happen in tandem with the research-and-prototyping phase of the designer's work.

Since we have a designer and statement of work, I propose marking this task as complete.
