### ISSUE TITLE
Develop roadmap for accessibility improvements

### ISSUE THREAD

**Issue by kariljordan** [carpentries/strategic-plan#34]
[Goal 2](https://github.com/carpentries/strategic-plan/blob/master/STRATEGIC-PLAN.md#goal-2-intentionally-incorporate-equity-inclusion-and-accessibility-to-support-a-diverse-community) of the Carpentries Strategic Plan is to _**Intentionally incorporate equity, inclusion, and accessibility to support a diverse community.**_ One of the objectives under this goal is:
- Create a roadmap for improving the accessibility of our lessons, lesson infrastructure, online resources, and sign-up workflows for teaching workshops.

Currently, instructors sign up for Centrally-Organised (CO) workshops via a [google spreadsheet](https://docs.google.com/spreadsheets/d/1YhTAzEalDqKUowgej7aRa7E1K0XcB6ZezoVUt6VN2qY/edit#gid=0). The Workshop Administration Team (WAT) would like to automate this process in AMY to reduce bias and ambiguity when selecting instructors. The instructors would be chosen based on the criteria identified: 

- frequency of most recent workshop taught
- location
- new or experienced instructors
- availability 

This issue will track progress for the following:
- [x] Creation of a roadmap to outline what accessibility improvements are being undertaken and when.
- [ ] Improved instructor sign-up workflow

**Comment by sheraaronhurt** [comment]
This will be what will be the focus of Q2 for the Workshop Admin Team. This term we were onboarding a new Workshop Administrator and finalizing the Automation.

**Comment by kariljordan** [comment]
Note from @ErinBecker: Sher and I discussed this at our meeting this week. My interpretation is that much of this work is already being done, but by different teams and not in a coordinated way that will make it easy to report back on progress to the EC. I talked with Sher about the work I am aware of already being done on these various items and asked her to get in touch with the individuals leading that work (including Zhian and Serah). My impression is that she would gather information from the various sources and make a comprehensive document and/or place to track progress, so that all involved parties can stay aware of the different aspects of this work and so that we can work in a more coordinated way.

**Comment by sheraaronhurt** [comment]
[Here is the link](https://docs.google.com/spreadsheets/d/1-MW-aZ8LqTvqxFJm3XqQHXExMMvglOvB1jgv_zVa_dc/edit#gid=0) that has the tentative schedule for completing each item provided by the Team Leads.

**Comment by sheraaronhurt** [comment]
The link provided above is the deliverable for this issue. All of the items are still being worked on by the individual teams.

**Comment by kariljordan** [comment]
@sheraaronhurt the roadmap is linked, however, the improved instructor sign-up workflow is a work in progress. I will update the label for this issue to add Q4.

**Comment by sheraaronhurt** [comment]
The WAT is progressing forward with the instructor sign-up workflow. This will be completed and implemented by April 2022

**Comment by sheraaronhurt** [comment]
This project is progressing forward nicely! @maneesha conducted a demo for the team on Thursday, June 9th and have identified Instructors to test and provide feedback. The timeline for moving forward is as follows: 

- By June 24: Review by CoreTeam and Instructors 
- June 27-July 1: Maneesha reviews and consolidates feedback to give to Piotr
- Month of July: Piotr makes changes based on our feedback
- Official release Monday August 1

**Comment by sheraaronhurt** [comment]
This project will be delayed. @maneesha is devising a new plan that will align with all of the upcoming changes including staffing and other technical projects that this will impact. 

Once @maneesha provides a new timeline I will update it here.

**Comment by sheraaronhurt** [comment]
Here is the tentative update for the project: 

**September 5, 2022**
- Piotr will have implemented all the features requested above.

**September 5-16 2022**

-     Core Team will do a final review of the fixes Piotr has made.
-     Workshop Admin Team and Instructor Training Team will communicate with Instructors and Trainers that these changes are coming.
-     Maneesha will prepare queries and scripts that feed our website and other automations that will need to be updated when these data structures change.

**September 19-30, 2022**

-     Piotr will make any final changes if needed and prepare for the official launch of all features.
-     Maneesha will continue to prepare queries and scripts that feed our website and other automations that will need to be updated when these data structures change.

**Monday, October 2, 2022**

-     Official launch of all features
-     Workshop Admin Team will transfer all information from current spreadsheet to AMY (should be done on this day)
-     Instructor Team will update all Trainer badges to use the ROLE feature rather than the Trainer Alumni badge (should be done sometime that week)

**2022 Q4 or 2023 Q1**

-     Plan for and implement deactivation of Instructors who have not been teaching or who have requested to go inactive.

**Comment by kariljordan** [comment]
@sheraaronhurt has added _**Develop a workflow for responding to accessibility needs of Learners/Instructorsthe**_ to the roadmap for the Workshop Admin Team. @brynnelliott is going to join an upcoming Team Lead meeting to refresh everyone on the list of accessibility improvements and to see how to ensure these items are in their roadmaps/on their radar to develop collaboration plans.

Now that we have a roadmap for accessibility improvements and timeline for implementing the improved workflow for instructor sign-ups, we can close this issue.
