### ISSUE TITLE
Create lesson template prototype for Carpentries Incubator Program

### ISSUE THREAD

**Issue by kariljordan** [carpentries/strategic-plan#9]
[Goal 4](https://github.com/carpentries/strategic-plan/blob/master/README.md#goal-4-facilitate-the-creation-and-maintenance-of-relevant-high-quality-community-curated-curricula) of our strategic plan is to "Facilitate the creation and maintenance of relevant, high-quality, Community-curated curricula." 

Two objectives under this goal are: 
- Improve the overall experience for contributors by developing accessible templates and documentation, revising existing processes and documentation for novices, and curating contribution opportunities for new contributors.
- Empower Community members to develop lessons by lowering barriers to contributing to The Carpentries Incubator program and making the lesson development and release process more transparent.

@zkamvar is working on developing a lesson template prototype to reduce the technological barrier to developing a new lesson.

**Comment by zkamvar** [comment]
## Update

We have been tackling this goal in several ways and have identified a clear path forward as outlined in our blog post: https://carpentries.org/blog/2020/08/lesson-template-design/. To date, we have prototyped resources for creating, maintaining, and validating lessons using RMarkdown, which allows people to write markdown lessons that can be evaluated in R, python, SQL, Bash, etc.

Below is a list of where we are as of 2020-08-19 (with permanent links, so be aware that the projects will have moved on since then): 

 - A prototype for a lesson template is in the works with the [{sandpaper}](https://github.com/zkamvar/sandpaper/tree/f02323df3e7e4decfdafe70523f589940f544685r#readme) R package that shifts the dependency stack from Ruby + Bundler + Jekyll + Make + Python to R + RStudio.
 - We are formally separating the style from the content into the [{varnish}](https://github.com/zkamvar/varnish/tree/4d801126c39bebca15ba1e644a4a33f52197c0be#readme) package to allow for seamless updates to the style and avoid merge conflicts with lessons
 - A new system for creating nested callout blocks in our lessons via RMarkdown is in the works with [{dovetail}](https://github.com/carpentries/dovetail/tree/8151b5f7bebb13bc7745d506ccc41e14dd3d9f25#readme).
 - Exploration of parsing and validating the markdown lessons is being implemented in [{pegboard}](https://github.com/carpentries/pegboard/tree/720c419824fd52834203801cb841d479e82d56a7#readme)

In addition, we have created a resource for building lessons without needing the standard development stack, and instead relying on Docker, called [lesson-docker](https://github.com/carpentries/lesson-docker/tree/aaa302a1a19cfc7007bf80f6214f8f2ad2a5deaa#readme). It has been well received by members of the maintainer community (though, is designed to be a stopgap solution).

**Comment by kariljordan** [comment]
@ErinBecker pointed out that the [launch of our Help Wanted page](https://carpentries.org/blog/2020/10/announcing-the-new-help-wanted-page/) goes a long way towards the last goal of curating contribution opportunities.

**Comment by zkamvar** [comment]
Update on the new lesson template
---------------------------------

This addresses the following aspect:

> Improve the overall experience for contributors by developing accessible templates and documentation, revising existing processes and documentation for novices

As of 2021-04-09 we have our new template called [{sandpaper}] entering alpha phase. A landscape view of the template (living document) can be found at https://zkamvar.github.io/stunning-barnacle/ the rollout plan (also a living document) for the alpha phase that defines the audience and components can be found at https://zkamvar.github.io/stunning-barnacle/rollout.html. At the moment [documentation for the new template](https://zkamvar.github.io/sandpaper-docs/) is built using the new template and ([the current rendered snapshot lives here](https://github.com/zkamvar/sandpaper-docs/tree/1aa4317bdf1698eae2e7e1fe372f4b8a10dd5b26)). 

The front-end of the template has finished the user experience testing and design phase. We are currently working to implement it as functional web pages that work with [{sandpaper}]. 

The new lesson template is about to enter the Alpha phase of testing in the following paradigm:

 - Alpha: This is framework testing where we don't have a polished product and focus on finding bugs in the current template and major usability issues among our maintainers. 
 - Beta: This is a soft release phase where we will convert some incubator and unofficial lessons to the new template and let them be worked on in the wild. 
 - Release Candidate: we will convert a subset of core lessons to the new template to stress test instructor contributions.
 - Release: Template is considered official and the carpentries/styles will officially be maintained for lessons for one more year beyond that date. 

[{sandpaper}]: https://github.com/carpentries/sandpaper/tree/0ec9b9d4dabdf4d2e1edade8569b959bfefa6eca

**Comment by tobyhodges** [comment]
> - Improve the overall experience for contributors by developing accessible templates and documentation, revising existing processes and documentation for novices, and curating contribution opportunities for new contributors.

The alpha testing process is nearing completion for the new lesson infrastructure. @zkamvar has received feedback from community members with a range of different levels of familiarity with the tools and processes involved in creating a lesson. Zhian is incorporating this feedback as he continues with the development process. Alpha testing helped to identify a number of minor issues with the functionality and usability of the new infrastructure but no major blockers were encountered. The next step will be a soft beta release as described above.

**Comment by fmichonneau** [comment]
We will have the new template ready to use with Zhian's infrastructure by the end of November so we can expect a beta launch of the lesson template for the Carpentries Incubator before the end of 2021.

**Comment by zkamvar** [comment]
> Improve the overall experience for contributors by developing accessible templates and documentation, revising existing processes and documentation for novices, and curating contribution opportunities for new contributors.

We received the final template near the end of December 2021. Progress was made to incorporate the template into our infrastructure by mid-January, and The Carpentries Workbench was officially announced on 2022-01-31: https://carpentries.org/blog/2022/01/live-lesson-infrastructure/. The new frontend is rated to WCAG AAA standards on readability and contrast. It follows recommended guidelines for links and navigation. 
We have created two template repositories:

1. [A template for markdown lessons](https://github.com/carpentries/workbench-template-md)
2. [A template for R Markdown lessons](https://github.com/carpentries/workbench-template-rmd)


Maintainer reception has been largely positive. Live testing with @tobyhodges and @MCMaurer reveal fewer issues and a much better experience with the process for editing and building lessons as compared with our former template. Two individuals have reached out to let me know that the workbench fits exactly with their needs in building lessons outside of The Carpentries, which indicates the broader applicability of The Workbench.


We are in the process of drafting a Beta phase for the infrastructure that will involve structured and unstructured feedback from Lesson Maintainers, Instructors, and Trainers. This beta testing will commence in Q2 2022.

**Comment by kariljordan** [comment]
Regarding closing this issue, @tobyhodges commented in the strategic plan roadmap: "On the other hand, it overlaps in a slightly fuzzy way with "Empower Community members to develop lessons by lowering barriers to contributing to The Carpentries Incubator program and making the lesson development and release process more transparent" for year 3 - maybe we can leave this marked as complete, on the grounds that that year 3 goal will keep us honest for this target?"

I agree that this issue can be closed on we can track the next steps with the lesson development release process. @zkamvar are you comfortable closing this issue?

**Comment by zkamvar** [comment]
Yes, we can close this issue.

The workbench is now in the beta phase of testing (https://carpentries.org/blog/2022/05/workbench-beta/) and there are currently several lessons that use (and have been using) the workbench, thus, it is out of prototype stage.
